spring:
  application:
    name: eureka-server

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    wait-time-in-ms-when-sync-empty: 0
 
zuul:
  prefix: /api
  routes:
    users:
      path: /user/**
      url: http://localhost:8300/rest/user
    comments:
      path: /comment/**
      url: http://localhost:8300/rest/comment
    books:
      path: /book/**
      url: http://localhost:8300/rest/book
    bookChapters:
      path: /bookChapter/**
      url: http://localhost:8300/rest/bookChapter